# Generated by Django 2.0.2 on 2018-02-23 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_auto_20180223_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='county',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AddField(
            model_name='owner',
            name='email',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AddField(
            model_name='owner',
            name='first_name',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AddField(
            model_name='owner',
            name='last_name',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AddField(
            model_name='owner',
            name='lat',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='owner',
            name='locality',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AddField(
            model_name='owner',
            name='lon',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='owner',
            name='phone',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AddField(
            model_name='owner',
            name='postal_code',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AddField(
            model_name='owner',
            name='route',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AddField(
            model_name='owner',
            name='state',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AddField(
            model_name='owner',
            name='street_number',
            field=models.IntegerField(default=None),
        ),
    ]
