# Generated by Django 2.0.2 on 2018-03-08 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0007_auto_20180308_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='lat',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='lng',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='street_number',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
