# Generated by Django 2.0.2 on 2018-03-08 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0008_auto_20180308_0325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_name', models.CharField(default='', max_length=128)),
                ('first_name', models.CharField(default='', max_length=128)),
                ('last_name', models.CharField(default='', max_length=128)),
                ('phone', models.CharField(default='', max_length=128)),
                ('email', models.CharField(default='', max_length=128)),
                ('home', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='rest.Parcel')),
            ],
        ),
    ]
