# Generated by Django 2.0.2 on 2018-03-16 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0010_auto_20180308_0427'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='owner',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='rest.Owner'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='home',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homeowner', to='rest.Parcel'),
        ),
    ]
