# Generated by Django 2.0.2 on 2018-03-19 17:10

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rest', '0013_auto_20180319_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formatted_address', models.CharField(default='', max_length=128)),
                ('street_number', models.IntegerField(default=None, null=True)),
                ('route', models.CharField(default='', max_length=128)),
                ('city', models.CharField(default='', max_length=128)),
                ('county', models.CharField(default='', max_length=128)),
                ('state', models.CharField(default='', max_length=128)),
                ('postal_code', models.CharField(default='', max_length=128)),
                ('lat', models.FloatField(default=None, null=True)),
                ('lng', models.FloatField(default=None, null=True)),
                ('place_id', models.CharField(default='', max_length=128)),
                ('place_type', models.CharField(default='', max_length=128)),
                ('estated', django.contrib.postgres.fields.jsonb.JSONField(default=None)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='owner',
            name='users',
        ),
        migrations.RemoveField(
            model_name='parcel',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Owner',
        ),
        migrations.DeleteModel(
            name='Parcel',
        ),
    ]
