# Generated by Django 2.0.2 on 2018-03-19 17:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0014_auto_20180319_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
