# Generated by Django 2.0.2 on 2018-03-23 23:33

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rest', '0016_auto_20180319_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_premium', models.BooleanField()),
                ('premium_data', django.contrib.postgres.fields.jsonb.JSONField(default=None, null=True)),
                ('user_data', django.contrib.postgres.fields.jsonb.JSONField(default=None, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='lead',
            name='estated',
        ),
        migrations.AddField(
            model_name='lead',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='formatted_address',
            field=models.CharField(default='', max_length=128, unique=True),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('leaddata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rest.LeadData')),
            ],
            bases=('rest.leaddata',),
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('leaddata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rest.LeadData')),
            ],
            bases=('rest.leaddata',),
        ),
        migrations.AddField(
            model_name='leaddata',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='contacts',
            field=models.ManyToManyField(blank=True, to='rest.Contact'),
        ),
        migrations.AddField(
            model_name='lead',
            name='properties',
            field=models.ManyToManyField(blank=True, to='rest.Property'),
        ),
    ]
