# Generated by Django 2.0.2 on 2018-03-24 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0018_remove_leaddata_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaddata',
            old_name='premium_data',
            new_name='data',
        ),
        migrations.RemoveField(
            model_name='leaddata',
            name='user_data',
        ),
    ]
