# Generated by Django 2.0.2 on 2018-03-28 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0021_auto_20180326_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='raw_address',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='contact',
            name='raw_name',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='property',
            name='formatted_address',
            field=models.CharField(default='', max_length=128),
        ),
    ]
