# Generated by Django 2.0.2 on 2018-02-23 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='county',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='email',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='locality',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='lon',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='route',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='state',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='street_number',
        ),
    ]
