# Generated by Django 2.0.2 on 2018-02-27 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0004_auto_20180227_0046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parcel',
            old_name='locality',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='parcel',
            old_name='lon',
            new_name='lng',
        ),
        migrations.AddField(
            model_name='parcel',
            name='place_id',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AddField(
            model_name='parcel',
            name='place_type',
            field=models.CharField(default=None, max_length=128),
        ),
    ]
