# Generated by Django 2.0.2 on 2018-02-27 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0005_auto_20180227_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='email',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='owner',
            name='first_name',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='owner',
            name='last_name',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='owner',
            name='phone',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='city',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='county',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='formatted_address',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='place_id',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='place_type',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='postal_code',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='route',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='state',
            field=models.CharField(default='', max_length=128),
        ),
    ]
