# Generated by Django 2.0.2 on 2018-03-08 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0006_auto_20180227_0113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='parcel_ptr',
        ),
        migrations.DeleteModel(
            name='Owner',
        ),
    ]
